title:              Nevzat Çağlayan
tagline:            
description:        Nevzat Çağlayan Kişisel Blog sayfası.
url:                https://nevzat-caglayan.github.io

author:
  name:             Nevzat Çağlayan
  url:              https://nevzat-caglayan.github.io/
  email:            nevcaglayan@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
